master:
  replicaCount: 1
  nodeSelector:
    spark-role: master

worker:
  replicaCount: 2
  nodeSelector:
    spark-role: worker

image:
  registry: docker.io
  repository: bitnami/spark
  tag: 3.5.1-debian-12-r8

imagePullSecrets:
  - name: myregistrykey

